version: "3.8"

services:
    php:
        build:
            args:
                user: home
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: feedbackview
        container_name: feedbackview-app
        restart: always
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - feedbackview

    nginx:
        container_name: feedbackview-nginx
        image: nginx:1.23.1-alpine
        restart: always
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/feedbackview.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80
        networks:
            - feedbackview

networks:
    feedbackview:
        driver: bridge
